import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance/types';

export const skillsAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'skills',
  parts: [
    { id: 'root' }, { id: 'skillsHeader' }, { id: 'header' }, { id: 'tabs' }, { id: 'tab' },
    { id: 'sceneSearch' },
    { id: 'content' }, { id: 'installed' }, { id: 'sidebar' },
    { id: 'sidebarNav' }, { id: 'sidebarItem' },
    { id: 'sidebarItemIcon' }, { id: 'sidebarItemLabel' }, { id: 'sidebarItemCount' },
    { id: 'sidebarFooter' }, { id: 'sidebarHint' }, { id: 'main' },
    { id: 'filterAction' },
    { id: 'loading' }, { id: 'error' }, { id: 'empty' }, { id: 'list' }, { id: 'skeleton' },
    { id: 'pagination' }, { id: 'pageButton' }, { id: 'pageInfo' },
    { id: 'discover' },
    { id: 'discoverContent' }, { id: 'resultsInfo' },
    { id: 'matrix' }, { id: 'matrixSectionBar' }, { id: 'matrixSectionBtn' },
    { id: 'matrixChipList' }, { id: 'matrixChip' }, { id: 'matrixChipLabel' }, { id: 'matrixChipCount' },
    { id: 'suite' }, { id: 'suiteHero' }, { id: 'suiteHeroCopy' }, { id: 'suiteHeroActions' },
    { id: 'suiteModeToolbar' }, { id: 'suiteModes' }, { id: 'suiteModeTab' },
    { id: 'suiteModeTabLabel' }, { id: 'suiteLoading' },
    { id: 'suiteSections' }, { id: 'suiteSection' }, { id: 'suiteSectionLabel' },
    { id: 'suiteGrid' }, { id: 'suiteGroupCard' }, { id: 'suiteGroupHead' },
    { id: 'suiteGroupTitleWrap' }, { id: 'suiteGroupTitleRow' }, { id: 'suiteGroupTitle' },
    { id: 'suiteGroupCount' }, { id: 'suiteGroupActions' }, { id: 'suiteSkills' },
    { id: 'suiteSkill' }, { id: 'suiteSkillName' }, { id: 'suiteSkillStatus' },
  ],
  facets: [
    { id: 'tab', attribute: 'data-bf-tab', values: ['installed', 'discover'] },
    { id: 'category', attribute: 'data-bf-category', values: ['all', 'builtin', 'user', 'project', 'suite'] },
    { id: 'mode', attribute: 'data-bf-mode', values: ['agentic', 'Cowork', 'Claw', 'Team'] },
  ],
  states: [
    { id: 'hover', selector: { kind: 'self', suffix: ':hover' } },
    { id: 'focusVisible', selector: { kind: 'self', suffix: ':focus-visible' } },
    { id: 'disabled', selector: { kind: 'self', suffix: ':disabled' } },
    { id: 'active', selector: { kind: 'self', suffix: '[data-bf-state~="active"]' } },
    { id: 'empty', selector: { kind: 'self', suffix: '[data-bf-state~="empty"]' } },
    { id: 'shadowed', selector: { kind: 'self', suffix: '[data-bf-state~="shadowed"]' } },
    { id: 'builtin', selector: { kind: 'self', suffix: '[data-bf-state~="builtin"]' } },
    { id: 'enabled', selector: { kind: 'self', suffix: '[data-bf-state~="enabled"]' } },
    { id: 'dirty', selector: { kind: 'self', suffix: '[data-bf-state~="dirty"]' } },
    { id: 'covered', selector: { kind: 'self', suffix: '[data-bf-state~="covered"]' } },
  ],
};
