import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance/types';

export const skillsAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'skills',
  parts: [
    { id: 'root' },
    { id: 'content' }, { id: 'installed' }, { id: 'sidebar' }, { id: 'sidebarHeader' },
    { id: 'sidebarTitle' }, { id: 'sidebarSearch' }, { id: 'sidebarNav' }, { id: 'navSection' },
    { id: 'sidebarItem' }, { id: 'sidebarItemIcon' }, { id: 'sidebarItemLabel' }, { id: 'sidebarItemCount' },
    { id: 'main' }, { id: 'toolbar' },
    { id: 'contentHeader' }, { id: 'contentTitle' }, { id: 'contentSubtitle' },
    { id: 'filterAction' },
    { id: 'detailBadges' }, { id: 'detail' }, { id: 'detailDescriptionViewport' },
    { id: 'detailDescription' }, { id: 'detailMetadata' },
    { id: 'installedListHeader' }, { id: 'installedListTitle' }, { id: 'installedListCount' },
    { id: 'loading' }, { id: 'error' }, { id: 'empty' }, { id: 'list' }, { id: 'skeleton' },
    { id: 'installedCard' },
    { id: 'discover' }, { id: 'resultsInfo' },
    { id: 'groups' }, { id: 'groupsHeader' }, { id: 'groupList' },
    { id: 'groupTable' }, { id: 'groupListHeader' },
    { id: 'groupRow' }, { id: 'groupOpen' }, { id: 'groupActions' },
    { id: 'groupEditor' }, { id: 'groupMembers' }, { id: 'groupMember' },
    { id: 'matrixView' }, { id: 'matrixBody' }, { id: 'matrixSectionBar' }, { id: 'matrixSectionBtn' },
    { id: 'matrixChipList' }, { id: 'matrixChip' }, { id: 'matrixChipLabel' },
    { id: 'matrixChipCount' },
  ],
  facets: [
    { id: 'tab', attribute: 'data-bitfun-tab', values: ['all', 'builtin', 'user', 'project', 'groups', 'market', 'matrix'] },
    { id: 'category', attribute: 'data-bitfun-category', values: ['all', 'builtin', 'user', 'project', 'groups', 'market', 'matrix'] },
    { id: 'level', attribute: 'data-bitfun-level', values: ['user', 'project'] },
  ],
  states: [
    { id: 'hover', selector: { kind: 'self', suffix: ':hover' } },
    { id: 'focusVisible', selector: { kind: 'self', suffix: ':focus-visible' } },
    { id: 'disabled', selector: { kind: 'self', suffix: ':disabled' } },
    { id: 'active', selector: { kind: 'self', suffix: '[data-bitfun-state~="active"]' } },
    { id: 'empty', selector: { kind: 'self', suffix: '[data-bitfun-state~="empty"]' } },
    { id: 'shadowed', selector: { kind: 'self', suffix: '[data-bitfun-state~="shadowed"]' } },
    { id: 'builtin', selector: { kind: 'self', suffix: '[data-bitfun-state~="builtin"]' } },
    { id: 'enabled', selector: { kind: 'self', suffix: '[data-bitfun-state~="enabled"]' } },
    { id: 'dirty', selector: { kind: 'self', suffix: '[data-bitfun-state~="dirty"]' } },
    { id: 'covered', selector: { kind: 'self', suffix: '[data-bitfun-state~="covered"]' } },
  ],
};
