import type { ComponentMeta } from "../../registry.types";

export const selectMeta = {
  category: "form",
  description: "A native single-value selection control with grouped options, typed values, and independent leading and indicator regions.",
  maturity: "stable",
  name: "Select",
  props: [
    { name: "options", type: "readonly SelectOption[] (supports option-level testId and data-* attributes)" },
    { name: "value", type: "SelectValue" },
    { name: "defaultValue", type: "SelectValue" },
    { name: "placeholder", type: "string" },
    { name: "leading", type: "ReactNode" },
    { defaultValue: "md", name: "size", type: "sm | md | lg" },
    { defaultValue: "false", name: "invalid", type: "boolean" },
    { name: "onValueChange", type: "(value: SelectValue) => void" },
  ],
  states: ["default", "hover", "focus-visible", "invalid", "disabled"],
  tokens: [
    "color.field.background",
    "color.field.backgroundHover",
    "color.field.border",
    "color.field.borderHover",
    "color.field.borderFocus",
    "color.content.primary",
    "color.content.muted",
    "color.content.disabled",
    "color.status.danger.border",
    "color.status.danger.surface",
    "color.focus.ring",
    "control.height.sm",
    "control.height.md",
    "control.height.lg",
    "control.select.paddingInline",
    "control.select.leadingInset",
    "control.select.trailingInset",
    "control.select.contentGap",
    "control.select.indicatorSize",
    "control.select.radius",
    "font.family.control",
    "font.size.sm",
    "font.weight.regular",
  ],
} as const satisfies ComponentMeta;
