// Generated by scripts/mobile-ui-design-system.mjs. Do not edit.
import CoreGraphics

struct MobilePreviewMessage {
    let role: String
    let text: String
}

struct MobilePreviewScenario {
    let id: String
    let title: String
    let description: String
    let appearance: String
    let viewportWidth: CGFloat
    let viewportHeight: CGFloat
    let headerTitle: String
    let headerSubtitle: String
    let messages: [MobilePreviewMessage]
    let composerDraft: String
    let composerPlaceholder: String
    let connectionPhase: String
    let streaming: Bool
}

enum MobilePreviewScenarios {
    static let connectedConversation = MobilePreviewScenario(
        id: "connected-conversation",
        title: "Connected conversation",
        description: "A remote desktop is answering and the composer is ready.",
        appearance: "light",
        viewportWidth: 390,
        viewportHeight: 844,
        headerTitle: "统一移动端设计系统",
        headerSubtitle: "DESKTOP-KM3L4UI",
        messages: [MobilePreviewMessage(role: "user", text: "三端的组件和样式可以保持一致吗？"), MobilePreviewMessage(role: "assistant", text: "可以。共享视觉契约，三端继续使用原生渲染。")],
        composerDraft: "",
        composerPlaceholder: "向 BitFun 提问",
        connectionPhase: "connected",
        streaming: false
    )

    static let streamingDark = MobilePreviewScenario(
        id: "streaming-dark",
        title: "Streaming in dark mode",
        description: "An active turn exercises dark surfaces and the stop action.",
        appearance: "dark",
        viewportWidth: 390,
        viewportHeight: 844,
        headerTitle: "跨端视觉校验",
        headerSubtitle: "正在由 MacBook Pro 运行",
        messages: [MobilePreviewMessage(role: "user", text: "比较三端的输入框、消息气泡和标题栏。"), MobilePreviewMessage(role: "assistant", text: "正在生成原生截图，并按相同基线并排展示。")],
        composerDraft: "检查深色模式下的边框对比度",
        composerPlaceholder: "输入消息",
        connectionPhase: "connected",
        streaming: true
    )

    static let reconnectingWide = MobilePreviewScenario(
        id: "reconnecting-wide",
        title: "Reconnecting on a wide viewport",
        description: "A tablet-sized viewport keeps remote blocking states answerable.",
        appearance: "light",
        viewportWidth: 1024,
        viewportHeight: 768,
        headerTitle: "远程会话",
        headerSubtitle: "正在恢复连接",
        messages: [MobilePreviewMessage(role: "assistant", text: "连接暂时中断。恢复后会从上次游标继续。")],
        composerDraft: "",
        composerPlaceholder: "等待重新连接",
        connectionPhase: "reconnecting",
        streaming: false
    )
}
