// Generated by scripts/generate-agent-harness.mjs. Edit the shared contract instead.

export const HARNESS_IDS = ["Minimal", "Standard", "Ultimate", "Creative"] as const;
export type HarnessId = typeof HARNESS_IDS[number];
const aliases: ReadonlyMap<string, HarnessId> = new Map([
  ["Minimal", "Minimal"],
  ["minimal", "Minimal"],
  ["Standard", "Standard"],
  ["standard", "Standard"],
  ["balanced", "Standard"],
  ["agentic", "Standard"],
  ["Agentic", "Standard"],
  ["Ultimate", "Ultimate"],
  ["ultimate", "Ultimate"],
  ["Ultra", "Ultimate"],
  ["ultra", "Ultimate"],
  ["Creative", "Creative"],
  ["creative", "Creative"],
]);
const legacyWireIds: Record<HarnessId, string> = {
  Minimal: "minimal",
  Standard: "agentic",
  Ultimate: "Ultra",
  Creative: "Creative",
};
const configAliases: ReadonlyMap<string, HarnessId> = new Map([
  ["coding_shared", "Standard"],
]);
export function isHarnessId(id: string): id is HarnessId {
  return (HARNESS_IDS as readonly string[]).includes(id);
}
/** Use only at a built-in identity boundary; source-qualified/custom IDs stay intact. */
export function canonicalHarnessId(id: string | null | undefined): HarnessId | null {
  const key = id?.trim();
  return key ? aliases.get(key) ?? aliases.get(key.toLowerCase()) ?? null : null;
}
export function canonicalAgentId(id: string): string {
  return canonicalHarnessId(id) ?? id;
}
export function legacyAgentWireId(id: string): string {
  const harness = canonicalHarnessId(id);
  return harness ? legacyWireIds[harness] : id;
}
export function canonicalAgentConfigId(id: string): string {
  return configAliases.get(id) ?? canonicalAgentId(id);
}
