import type { ComponentMeta } from "../../registry.types";

export const buttonMeta = {
  category: "action",
  description: "A compact pill action with outline, filled, primary, and text presentation variants.",
  maturity: "stable",
  name: "Button",
  props: [
    { defaultValue: "outline", name: "variant", type: "outline | fill | primary | text" },
    { defaultValue: "md", name: "size", type: "xs | sm | md | lg" },
    { defaultValue: "neutral", name: "tone", type: "neutral | danger" },
    { defaultValue: "false", name: "loading", type: "boolean" },
    { name: "leadingIcon", type: "ReactNode" },
    { name: "trailingIcon", type: "ReactNode" },
  ],
  states: ["default", "hover", "active", "disabled"],
  tokens: [
    "color.action.neutral.border",
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surface",
    "color.action.neutral.surfaceHover",
    "color.action.neutral.surfacePressed",
    "color.action.primary.background",
    "color.action.primary.content",
    "color.action.primary.hover",
    "color.action.primary.pressed",
    "color.accent.default",
    "color.accent.hover",
    "color.accent.disabled",
    "color.focus.ring",
    "color.status.danger.border",
    "color.status.danger.content",
    "color.status.danger.surface",
    "control.height.sm",
    "control.height.md",
    "control.height.lg",
    "control.button.xsHeight",
    "control.button.xsPaddingInline",
    "control.button.xsLeadingIconSize",
    "control.button.xsTrailingIconSize",
    "type.meta.fontSize",
    "font.family.control",
    "font.size.sm",
    "font.weight.regular",
    "font.weight.semibold",
    "radius.pill",
  ],
} as const satisfies ComponentMeta;
