import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance';

export const chatInputAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'chat-input',
  parts: [
    { id: 'root' },
    { id: 'container' },
    { id: 'box' },
    { id: 'targetSwitcher' },
    { id: 'targetLabel' },
    { id: 'target' },
    { id: 'targetName' },
    { id: 'area' },
    { id: 'imageStrip' },
    { id: 'image' },
    { id: 'imagePreview' },
    { id: 'imageRemove' },
    { id: 'placeholder' },
    { id: 'commandPicker' },
    { id: 'commandHeader' },
    { id: 'commandList' },
    { id: 'commandItem' },
    { id: 'commandName' },
    { id: 'commandLabel' },
    { id: 'commandStatus' },
    { id: 'commandSection' },
    { id: 'commandEmpty' },
    { id: 'actionsLeft' },
    { id: 'actionsRight' },
    { id: 'boost' },
    { id: 'boostTrigger' },
    { id: 'boostMenu' },
    { id: 'boostItem' },
    { id: 'boostDivider' },
    { id: 'boostSubmenuTrigger' },
    { id: 'boostSubmenuPanel' },
    { id: 'boostSubmenuItem' },
    { id: 'boostSubmenuState' },
    { id: 'boostSubmenuManage' },
    { id: 'model' },
    { id: 'sendActions' },
    { id: 'sendButton' },
    { id: 'queuedBadge' },
  ],
  facets: [
    { id: 'target', attribute: 'data-bf-target', values: ['main', 'btw'] },
    { id: 'command', attribute: 'data-bf-command', values: ['actions', 'all', 'skills', 'modes'] },
    { id: 'commandItemKind', attribute: 'data-bf-command-item-kind', values: ['action', 'mode', 'skill', 'mcp'] },
    { id: 'action', attribute: 'data-bf-action', values: ['cancel', 'continue-interrupted', 'retry', 'send', 'split'] },
    { id: 'boostItemKind', attribute: 'data-bf-boost-item-kind', values: ['directive', 'agent', 'context', 'skill', 'additional-mode', 'manage'] },
  ],
  states: [
    { id: 'processing', selector: { kind: 'ancestorPart', part: 'root', suffix: '[data-bf-state~="processing"]' } },
    { id: 'recording', selector: { kind: 'self', suffix: '[data-bf-state~="recording"]' } },
    { id: 'multiline', selector: { kind: 'ancestorPart', part: 'root', suffix: '[data-bf-state~="multiline"]' } },
    { id: 'selected', selector: { kind: 'self', suffix: '[data-bf-state~="selected"]' } },
    { id: 'current', selector: { kind: 'self', suffix: '[data-bf-state~="current"]' } },
    { id: 'open', selector: { kind: 'self', suffix: '[data-bf-state~="open"]' } },
    { id: 'disabled', selector: { kind: 'self', suffix: '[data-bf-state~="disabled"]' } },
    { id: 'pending', selector: { kind: 'self', suffix: '[data-bf-state~="pending"]' } },
    { id: 'loading', selector: { kind: 'self', suffix: '[data-bf-state~="loading"]' } },
    { id: 'empty', selector: { kind: 'self', suffix: '[data-bf-state~="empty"]' } },
  ],
};
