import type { ComponentMeta } from "../../registry.types";

export const segmentedControlMeta = {
  category: "form",
  description: "A compact pill-shaped single-choice control that switches between a small set of exclusive modes.",
  maturity: "stable",
  name: "SegmentedControl",
  props: [
    { name: "options", type: "readonly SegmentedControlOption[]" },
    { name: "value", type: "string" },
    { name: "defaultValue", type: "string" },
    { name: "onValueChange", type: "(value: string) => void" },
    { defaultValue: "false", name: "disabled", type: "boolean" },
  ],
  states: ["selected", "unselected", "hover", "disabled"],
  tokens: [
    "color.action.neutral.content",
    "color.action.neutral.contentDisabled",
    "color.action.neutral.surfaceHover",
    "color.action.neutral.surfacePressed",
    "color.border.subtle",
    "color.content.primary",
    "color.focus.ring",
    "color.surface.raised",
    "color.surface.subtle",
    "control.segmentedControl.gap",
    "control.segmentedControl.padding",
    "control.segmentedControl.radius",
    "control.segmentedControl.segmentHeight",
    "control.segmentedControl.segmentPaddingInline",
    "control.segmentedControl.segmentGap",
    "control.segmentedControl.segmentRadius",
    "control.segmentedControl.iconSize",
    "type.meta.fontSize",
    "font.family.control",
    "font.weight.regular",
    "font.weight.medium",
  ],
} as const satisfies ComponentMeta;
