// Generated by scripts/generate-agent-harness.mjs. Edit the shared contract instead.

use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum HarnessId {
    #[serde(alias = "minimal")]
    Minimal,
    #[serde(alias = "standard")]
    #[serde(alias = "balanced")]
    #[serde(alias = "agentic")]
    #[serde(alias = "Agentic")]
    Standard,
    #[serde(alias = "ultimate")]
    #[serde(alias = "Ultra")]
    #[serde(alias = "ultra")]
    Ultimate,
    #[serde(alias = "creative")]
    Creative,
}

impl HarnessId {
    pub const ALL: [Self; 4] = [
        Self::Minimal,
        Self::Standard,
        Self::Ultimate,
        Self::Creative,
    ];
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::Minimal => "Minimal",
            Self::Standard => "Standard",
            Self::Ultimate => "Ultimate",
            Self::Creative => "Creative",
        }
    }
    pub fn from_legacy_id(id: &str) -> Option<Self> {
        match id.trim().to_ascii_lowercase().as_str() {
            "minimal" => Some(Self::Minimal),
            "standard" | "balanced" | "agentic" => Some(Self::Standard),
            "ultimate" | "ultra" => Some(Self::Ultimate),
            "creative" => Some(Self::Creative),
            _ => None,
        }
    }
    pub const fn legacy_wire_id(self) -> &'static str {
        match self {
            Self::Minimal => "minimal",
            Self::Standard => "agentic",
            Self::Ultimate => "Ultra",
            Self::Creative => "Creative",
        }
    }
    pub const fn legacy_ids(self) -> &'static [&'static str] {
        match self {
            Self::Minimal => &["minimal"],
            Self::Standard => &["standard", "balanced", "agentic", "Agentic"],
            Self::Ultimate => &["ultimate", "Ultra", "ultra"],
            Self::Creative => &["creative"],
        }
    }
}

/// Normalize a built-in identity at storage/protocol boundaries. Unknown IDs survive.
pub fn canonical_agent_id(id: &str) -> &str {
    HarnessId::from_legacy_id(id)
        .map(HarnessId::as_str)
        .unwrap_or(id)
}

pub fn canonical_agent_config_id(id: &str) -> &str {
    match id {
        "coding_shared" => "Standard",
        _ => canonical_agent_id(id),
    }
}

pub fn deserialize_agent_id<'de, D: serde::Deserializer<'de>>(
    deserializer: D,
) -> Result<String, D::Error> {
    let id = String::deserialize(deserializer)?;
    Ok(canonical_agent_id(&id).to_owned())
}

pub fn deserialize_optional_agent_id<'de, D: serde::Deserializer<'de>>(
    deserializer: D,
) -> Result<Option<String>, D::Error> {
    Ok(Option::<String>::deserialize(deserializer)?.map(|id| canonical_agent_id(&id).to_owned()))
}
