import type { AppearanceSurfaceDescriptor } from '@/infrastructure/appearance/types';

export const workbenchAppearanceDescriptor: AppearanceSurfaceDescriptor = {
  id: 'workbench',
  parts: [
    { id: 'workspace' },
    { id: 'collapsedNav' },
    { id: 'navArea' },
    { id: 'workspaceMaterial', propertyProfile: 'paint', visualRole: 'decoration' },
    { id: 'navDivider' },
    { id: 'sceneArea' },
    { id: 'sceneSurface' },
    { id: 'topBar' },
    { id: 'sceneActions' },
    { id: 'viewport' },
    { id: 'viewportClip' },
    { id: 'scene' },
    { id: 'loading' },
    { id: 'empty' },
  ],
  facets: [
    {
      id: 'sceneId',
      attribute: 'data-bitfun-scene-id',
      values: [
        'welcome',
        'session',
        'terminal',
        'git',
        'settings',
        'content',
        'miniapp',
        'profile',
        'agents',
        'skills',
        'miniapps',
        'pages',
        'browser',
        'assistant',
        'insights',
        'shell',
        'todos',
        'ecosystem-compatibility',
      ],
    },
  ],
  states: [
    { id: 'fullscreen', selector: { kind: 'self', suffix: '[data-bitfun-state~="fullscreen"]' } },
    { id: 'toolbar', selector: { kind: 'self', suffix: '[data-bitfun-state~="toolbar"]' } },
    { id: 'collapsed', selector: { kind: 'self', suffix: '[data-bitfun-state~="collapsed"]' } },
    { id: 'active', selector: { kind: 'self', suffix: '[data-bitfun-state~="active"]' } },
    { id: 'empty', selector: { kind: 'self', suffix: '[data-bitfun-state~="empty"]' } },
  ],
};
