import type { ComponentMeta } from "../../registry.types";

export const askUserMeta = {
  category: "flow-chat",
  description: "A controlled, accessible question card with responsive options, always-available custom answers, an optional path picker, submission feedback, and an answered disclosure summary.",
  maturity: "stable",
  name: "AskUser",
  props: [
    { name: "questions", type: "readonly AskUserQuestion[]" },
    { name: "questions[].header", type: "string" },
    { name: "questions[].inputPlaceholder", type: "string" },
    { defaultValue: "{}", name: "answers", type: "AskUserAnswers" },
    { defaultValue: "asking", name: "state", type: "AskUserState" },
    { name: "summaryLabel", type: "ReactNode" },
    { name: "summaryDetail", type: "ReactNode" },
    { defaultValue: "false", name: "expanded", type: "boolean" },
    { name: "onAnswersChange", type: "(questionId, values) => void" },
    { name: "onBrowseCustomAnswer", type: "(questionId) => void" },
    { name: "browseCustomAnswerLabel", type: "string" },
    { name: "onSubmit", type: "() => void" },
  ],
  states: [
    "asking",
    "selected",
    "submitting",
    "completed",
    "expanded",
    "loading",
    "error",
    "disabled",
  ],
  tokens: [
    "border.width.default",
    "color.action.neutral.content",
    "color.action.neutral.surfaceHover",
    "color.border.default",
    "color.border.strong",
    "color.border.subtle",
    "color.content.disabled",
    "color.content.inverse",
    "color.content.muted",
    "color.content.primary",
    "color.content.secondary",
    "color.field.borderActive",
    "color.field.placeholder",
    "color.focus.ring",
    "color.status.danger.border",
    "color.status.danger.content",
    "color.status.danger.surface",
    "color.status.success.content",
    "color.status.warning.border",
    "color.status.warning.content",
    "color.status.warning.surface",
    "color.surface.scene",
    "color.surface.subtle",
    "control.askUser.bodyGap",
    "control.askUser.bodyPadding",
    "type.body.sm.lineHeight",
    "control.askUser.descriptionMaxWidth",
    "control.askUser.headerHeight",
    "control.askUser.iconSize",
    "control.askUser.optionContentGap",
    "control.askUser.optionGap",
    "control.askUser.optionPaddingBlock",
    "control.askUser.optionPaddingInline",
    "control.askUser.questionOptionsGap",
    "control.askUser.questionPaddingInline",
    "control.askUser.summaryActionSize",
    "control.askUser.summaryPaddingBlock",
    "control.askUser.summaryPaddingInlineEnd",
    "control.askUser.summaryPaddingInlineStart",
    "control.hitTarget",
    "font.family.control",
    "font.size.sm",
    "font.size.xs",
    "font.weight.medium",
    "font.weight.regular",
    "font.weight.semibold",
    "lineHeight.base",
    "lineHeight.tight",
    "radius.base",
    "radius.lg",
    "radius.sm",
    "radius.xs",
    "shadow.lg",
    "space.1",
    "space.2",
    "space.3",
    "type.flow.title.letterSpacing",
    "type.overline.sm.fontFamily",
    "type.overline.sm.fontSize",
    "type.overline.sm.fontWeight",
    "type.overline.sm.letterSpacing",
    "type.overline.sm.lineHeight",
  ],
} as const satisfies ComponentMeta;
