import type { ComponentMeta } from "../../registry.types";

export const confirmDialogMeta = {
  category: "feedback",
  description: "Composes semantic confirmation content, optional preview material, async actions, and dismissal policy on the shared Dialog contract.",
  maturity: "stable",
  name: "ConfirmDialog",
  props: [
    { name: "open", type: "boolean" },
    { name: "title", type: "ReactNode" },
    { name: "message", type: "ReactNode" },
    { defaultValue: "warning", name: "type", type: "info | warning | error | success" },
    { name: "confirmText", type: "ReactNode" },
    { name: "secondaryText", type: "ReactNode" },
    { name: "cancelText", type: "ReactNode" },
    { name: "preview", type: "ReactNode" },
    { defaultValue: "false", name: "confirmDanger", type: "boolean" },
    { defaultValue: "true", name: "showCancel", type: "boolean" },
    { defaultValue: "false", name: "showCloseButton", type: "boolean" },
    { name: "pendingAction", type: "confirm | secondary | null" },
    { name: "onConfirm", type: "() => void | Promise<void>" },
    { name: "onSecondary", type: "() => void | Promise<void>" },
    { name: "onActionError", type: "(error: unknown, action: confirm | secondary) => void" },
    { name: "onOpenChange", type: "(open: false, reason: ConfirmDialogCloseReason) => void" },
  ],
  states: ["info", "warning", "error", "success", "pending"],
  tokens: [
    "color.content.primary",
    "color.content.secondary",
    "color.surface.subtle",
    "color.border.subtle",
    "color.status.info.content",
    "color.status.info.surface",
    "color.status.success.content",
    "color.status.success.surface",
    "color.status.warning.content",
    "color.status.warning.surface",
    "color.status.danger.content",
    "color.status.danger.surface",
    "layout.confirmDialog.contentGap",
    "layout.confirmDialog.messageGap",
    "layout.confirmDialog.iconSize",
    "layout.confirmDialog.iconGlyphSize",
    "layout.confirmDialog.previewMaxBlockSize",
    "layout.confirmDialog.previewPaddingBlock",
    "layout.confirmDialog.previewPaddingInline",
    "layout.confirmDialog.previewRadius",
    "font.family.control",
    "font.family.mono",
    "font.size.base",
    "font.size.xs",
  ],
} as const satisfies ComponentMeta;
